default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
      # fast lane
    - queues: "latency_10s"
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
      # middle lane
    - queues: "latency_10s,latency_5m"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
      # slow lane
    - queues: "latency_10s,latency_5m,literally_whenever,default,*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues: "video_conversion"
      threads: 1
      processes: 1
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
